USE movie_db;
INSERT INTO movie(Movie_ID,Movie_Type,Release_Date,Movie_Name,Movie_Lang,Movie_Desc,Movie_Length) 
values
(1,'Action','2022-11-09','Black Panther: Wakanda Forever','EN',"Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",161),
(2,'Horror','2022-10-06','Terrifier 2','EN',"After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",148),
(3,'Action','2022-10-19','Black Adam','EN',"Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",125),
(4,'Horror','2022-07-27','Orphan: First Kill','EN',"After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",99),
(5,'Anime','2022-08-06','One Piece Film Red','JP',"Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as 'otherworldly.' She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.",115),
(6,'Romance','2022-11-11','Falling for Christmas','EN','A newly engaged and spoiled hotel heiress finds herself in the care of a handsome, blue-collar lodge owner and his precocious daughter after getting total amnesia in a skiing accident.',93),
(7,'Romance','2022-10-06','Ticket to Paradise','EN','A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake they think they made 25 years ago.',104),
(8,'Drama','2022-10-07','All Quiet on the Western Front','EN','Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',143),
(9,'Drama','2022-11-11','Suzume','JP','A modern action adventure road story where a 17-year-old girl named Suzume helps a mysterious young man close doors from the outer side that are releasing disasters all over in Japan.',122),
(10,'Anime','2022-09-24','Jujutsu Kaisen 0','JP',"Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",105);
